FileSet {
  Name = "Catalog"
  Description = "Backup the catalog dump."
  Include {
    Options {
      Signature = XXH128
    }
    File = "/backups/bareos/catalog/bareos.sql" # database dump (shared volume, written by Director's RunBeforeJob)
  }
}
