FileSet {
  Name = "Catalog"
  Description = "Backup the catalog dump and Bareos configuration files."
  Include {
    Options {
      Signature = XXH128
    }
    File = "/backups/bareos/catalog/bareos.sql" # database dump (shared volume, written by Director's RunBeforeJob)
    File = "/etc/bareos"                  # configuration
  }
}
