Console {
  Name = bareos-mon
  Description = "Restricted console used by tray-monitor to get the status of the director."
  Password = "/L8mhwtXasKsEihvIQPWqh4tB+5g1yI5BCRFgffUYjKh"
  CommandACL = status, .status
  JobACL = *all*
}
