Storage {
  Name = File
  Address = bareos-sd                # N.B. Use a fully qualified name here (do not use "localhost" here).
  Password = "a0JMGQgFWHAUWfHnMaBtNJ6Ouhz3a7VsPi/ThvJDrPyn"
  Device = FileStorage
  Media Type = File
  Maximum Concurrent Jobs = 10 # should be high enough to allow the use all configure devices
}
